### ISSUE TITLE
detect if user is adding his own text (not chip) and show him error

### ISSUE THREAD

**Issue by FareehaRqzaq** [OfficialAmal/ChipLayout#15]
How can I prevent user to adding his own text while and allow him to enter only chip.. Not user's text

**Comment by OfficialAmal** [comment]
you want chip to be only selected from suggestion list ?

**Comment by OfficialAmal** [comment]
in that case implement ChipItemChangeListener and check the values every time new chip added, you can call getText() which returns list of vales. check each value against the adaptor values, if the value doesn't exist in adaptor you can highlight that chip by calling highlightChipAt(int pos, Drawable bgDrawable, int textColor) or highlightChipAt(int pos, int bgColor, int textColor) or you can remove that chip by calling removeChipAt(int pos).
