### ISSUE TITLE
Drawable fails to import when compiling through Gradle

### ISSUE THREAD

**Issue by MichaelOVertolli** [OfficialAmal/ChipLayout#3]
This line:

`custom:chipDrawable_="@drawable/round_corner_drawable"
custom:chipLayoutDrawable_="@drawable/edittext_theme_landing_page"`

is the problem. 

The only way I can get it to work is by manually copying the relevant res files.

**Comment by OfficialAmal** [comment]
"@drawable/ " ..there should be something in your drawable folder
