### ISSUE TITLE
Programmatically Indexing Chips for Removal

### ISSUE THREAD

**Issue by MichaelOVertolli** [OfficialAmal/ChipLayout#5]
It would be nice to have a more elegant way to remove chips programmatically (mainly to reset the ChipLayout viewgroup) without having to index each chip by its view.

Elegant solutions are stifled by two main problems:
1. There are elements of the ChipLayout viewgroup that are not chips, so `chip.removeAllViews()` destroys those elements.
2. The `pos` values change as chips are removed, so storing them in `onChipAdded`/`onChipRemoved` does not work.

The best solution I came up with was to store the corresponding views of the `pos` values in `onChipAdded` with `chip.getChildAt(pos)` then convert back to the `pos` value when I want to programmatically remove some_chip with `chip.removeChipAt(chip.indexOfChild(some_chip_view))`. Obviously, this is less than ideal.

**Comment by michelelaferla** [comment]
I solved this by actually using the following: `chip.removeAllViews();` In my case however I was searching through an array to check if a string exists. If it doesn't, then the user can add a new record to the array and clear the view.

**Comment by OfficialAmal** [comment]
removeAllChips is added in 1.0.5
