### ISSUE TITLE
Most of the Custom Attributes aren't working as desired

### ISSUE THREAD

**Issue by CeJienAJPC** [OfficialAmal/ChipLayout#9]
The following attributes aren't working as expected.

        custom:chipDrawable_="@drawable/background_rectangle_indicator"
        custom:chipPadding_="@dimen/dp_16"
        custom:chipTextPadding_="@dimen/dp_16"
        custom:deleteIcon_="@drawable/icon_clear"
        custom:hint_="@string/mecoba_ChipLayout_Hint_Tags"

Am I missing something?

Thanks

**Comment by OfficialAmal** [comment]
Are you using - xmlns:custom="http://schemas.android.com/apk/res-auto".
